/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rtkay.kayla;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

public class App extends Application {
    private double xOffset = 0;
    private double yOffset = 0;
    public String getName() {
        return "Kayla!";
    }

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        StackPane root = FXMLLoader.load(getClass().getResource("main.fxml"));
        Scene scene  = new Scene(root);
        scene.getStylesheets().add(getClass().getResource("theme/fonts/selector.css").toExternalForm());
        primaryStage.setTitle(getName());
        primaryStage.initStyle(StageStyle.UNDECORATED);
        root.setOnMousePressed(e -> {
            xOffset = primaryStage.getX() - e.getScreenX();
            yOffset = primaryStage.getY() - e.getScreenY();
        });
        root.setOnMouseDragged(e -> {
            primaryStage.setX(e.getScreenX() + xOffset);
            primaryStage.setY(e.getScreenY() + yOffset);
        });
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
