/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rtkay.kayla;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAName() {
        App classUnderTest = new App();
        assertNotNull("app should have a name", classUnderTest.getName());
    }
}
